spring:
  application:
    name: mcp-server-webflux
    version: 1.0.0
  ai:
    mcp:
      server:
        enabled: true
        type: async
        name: mcp-server-webflux
        version: 1.0.0
        sse-message-endpoint: /mcp/messages
        sse-endpoint: /sse
        capabilities:
          completion: true
          tool: true
          prompt: true
          resource: true

server:
  port: 8082
